/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package scholarshipmanagement;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SARK
 */
public class Dashboard extends javax.swing.JInternalFrame {
    String StudentId;
    public Connection connection;

    /** Creates new form PackageInfo */
    public Dashboard() {
        initComponents();
    }
    public Dashboard(String StudentId) {
        initComponents();
        universityNo.setText(getValue("Select count(UniID) from University"));
        professorNo.setText(getValue("Select count(ProfID) from Professor"));
        scholarshipNo.setText(getValue("Select count(ScholarshipID) from Scholarship"));
        studentNo.setText(getValue("Select count(StudentID) from Student"));
        cgpa4.setText(getValue("Select count(StudentID) from Student where AverageGrade between 2.01 and 2.50"));
        cgpa3.setText(getValue("Select count(StudentID) from Student where AverageGrade between 2.51 and 3.00"));
        cgpa2.setText(getValue("Select count(StudentID) from Student where AverageGrade between 3.01 and 3.50"));
        cgpa1.setText(getValue("Select count(StudentID) from Student where AverageGrade between 3.51 and 4.00"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        scholarshipNo = new javax.swing.JTextField();
        professorNo = new javax.swing.JTextField();
        universityNo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cgpa1 = new javax.swing.JTextField();
        cgpa2 = new javax.swing.JTextField();
        cgpa3 = new javax.swing.JTextField();
        cgpa4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(750, 570));
        setMinimumSize(new java.awt.Dimension(750, 570));
        setPreferredSize(new java.awt.Dimension(1320, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Scholarship Info");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(700, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1310, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Number Of University:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Number Of Professor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Number Of Scholarship:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 30));

        scholarshipNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scholarshipNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        scholarshipNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        scholarshipNo.setEnabled(false);
        getContentPane().add(scholarshipNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 190, 30));

        professorNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        professorNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        professorNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        professorNo.setEnabled(false);
        getContentPane().add(professorNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 190, 30));

        universityNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        universityNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        universityNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        universityNo.setEnabled(false);
        getContentPane().add(universityNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 190, 30));

        jPanel2.setBackground(new java.awt.Color(15, 19, 52));
        jPanel2.setPreferredSize(new java.awt.Dimension(6, 450));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Number Of Student:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CGPA Range:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        studentNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentNo.setEnabled(false);
        getContentPane().add(studentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Student Info");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("3.51    -    4.00:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        cgpa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgpa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cgpa1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cgpa1.setEnabled(false);
        cgpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpa1ActionPerformed(evt);
            }
        });
        getContentPane().add(cgpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 352, 100, 30));

        cgpa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgpa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cgpa2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cgpa2.setEnabled(false);
        getContentPane().add(cgpa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 100, 30));

        cgpa3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgpa3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cgpa3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cgpa3.setEnabled(false);
        cgpa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpa3ActionPerformed(evt);
            }
        });
        getContentPane().add(cgpa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 100, 30));

        cgpa4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgpa4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cgpa4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cgpa4.setEnabled(false);
        getContentPane().add(cgpa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 100, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("2.01    -    2.50:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("2.51    -    3.00:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("3.01    -    3.50:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1310, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String  getValue(String query)
    {
        String val = new String();
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Scholarship;selectMethod=cursor", "sa", "123456");

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery(query);
            
            resultSet.next();
                 
            try
            {
                val  = resultSet.getString(1).toString();
            }
            catch(Exception e)
            {
                val = "0";
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return val;
    
    }
    
    private void cgpa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpa3ActionPerformed

    private void cgpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpa1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cgpa1;
    private javax.swing.JTextField cgpa2;
    private javax.swing.JTextField cgpa3;
    private javax.swing.JTextField cgpa4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField professorNo;
    private javax.swing.JTextField scholarshipNo;
    private javax.swing.JTextField studentNo;
    private javax.swing.JTextField universityNo;
    // End of variables declaration//GEN-END:variables

}
