/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarshipmanagement;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author SARK
 */
public class ProfessorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    String ProfId;
    
    
    public ProfessorDashboard() {
        initComponents();
        ProfessorProfile temp = new ProfessorProfile();
        jDesktopPane1.add(temp).setVisible(true);
    }
    
     public ProfessorDashboard(String ProfId) {
        initComponents();
        this.ProfId = ProfId;
        jDesktopPane1.removeAll();
        ProfessorProfile temp = new ProfessorProfile(this.ProfId);
        jDesktopPane1.add(temp).setVisible(true);
        //admin  = (new ConnectMSSQL().getAdminInfo("where EmployeeId = '"+AdminId+"'")).get(0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inboxPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        professorPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        universityPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scholarshipPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        studentPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        researchPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        coursePanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 570));
        setMinimumSize(new java.awt.Dimension(1050, 570));
        setPreferredSize(new java.awt.Dimension(1600, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 570));

        inboxPanel.setBackground(new java.awt.Color(51, 0, 51));
        inboxPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        inboxPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inboxPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inboxPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inboxPanelMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(15, 19, 52));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scholarshipmanagement/inbox.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(15, 19, 52));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inbox");

        javax.swing.GroupLayout inboxPanelLayout = new javax.swing.GroupLayout(inboxPanel);
        inboxPanel.setLayout(inboxPanelLayout);
        inboxPanelLayout.setHorizontalGroup(
            inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inboxPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        inboxPanelLayout.setVerticalGroup(
            inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inboxPanelLayout.createSequentialGroup()
                .addGroup(inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        professorPanel.setBackground(new java.awt.Color(51, 0, 51));
        professorPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        professorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                professorPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                professorPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                professorPanelMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(15, 19, 52));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Profile");

        jLabel8.setBackground(new java.awt.Color(15, 19, 52));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\professor.png")); // NOI18N

        javax.swing.GroupLayout professorPanelLayout = new javax.swing.GroupLayout(professorPanel);
        professorPanel.setLayout(professorPanelLayout);
        professorPanelLayout.setHorizontalGroup(
            professorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        professorPanelLayout.setVerticalGroup(
            professorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorPanelLayout.createSequentialGroup()
                .addGroup(professorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        universityPanel.setBackground(new java.awt.Color(51, 0, 51));
        universityPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        universityPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                universityPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                universityPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                universityPanelMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(15, 19, 52));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("University");

        jLabel9.setBackground(new java.awt.Color(15, 19, 52));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\education.png")); // NOI18N

        javax.swing.GroupLayout universityPanelLayout = new javax.swing.GroupLayout(universityPanel);
        universityPanel.setLayout(universityPanelLayout);
        universityPanelLayout.setHorizontalGroup(
            universityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, universityPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        universityPanelLayout.setVerticalGroup(
            universityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(universityPanelLayout.createSequentialGroup()
                .addGroup(universityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        scholarshipPanel.setBackground(new java.awt.Color(51, 0, 51));
        scholarshipPanel.setForeground(new java.awt.Color(255, 255, 255));
        scholarshipPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        scholarshipPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scholarshipPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scholarshipPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scholarshipPanelMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(15, 19, 52));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Scholarship");

        jLabel11.setBackground(new java.awt.Color(15, 19, 52));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\scholarship.png")); // NOI18N

        javax.swing.GroupLayout scholarshipPanelLayout = new javax.swing.GroupLayout(scholarshipPanel);
        scholarshipPanel.setLayout(scholarshipPanelLayout);
        scholarshipPanelLayout.setHorizontalGroup(
            scholarshipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scholarshipPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        scholarshipPanelLayout.setVerticalGroup(
            scholarshipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scholarshipPanelLayout.createSequentialGroup()
                .addGroup(scholarshipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        studentPanel.setBackground(new java.awt.Color(51, 0, 51));
        studentPanel.setForeground(new java.awt.Color(255, 255, 255));
        studentPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        studentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentPanelMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(15, 19, 52));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student");

        jLabel12.setBackground(new java.awt.Color(15, 19, 52));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\information.png")); // NOI18N

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        dashboardPanel.setBackground(new java.awt.Color(51, 0, 51));
        dashboardPanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(15, 19, 52));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dashboard");

        jLabel13.setBackground(new java.awt.Color(15, 19, 52));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\dash.png")); // NOI18N

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        researchPanel.setBackground(new java.awt.Color(51, 0, 51));
        researchPanel.setForeground(new java.awt.Color(255, 255, 255));
        researchPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        researchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                researchPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                researchPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                researchPanelMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(15, 19, 52));
        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Research Paper");

        jLabel15.setBackground(new java.awt.Color(15, 19, 52));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\research.png")); // NOI18N

        javax.swing.GroupLayout researchPanelLayout = new javax.swing.GroupLayout(researchPanel);
        researchPanel.setLayout(researchPanelLayout);
        researchPanelLayout.setHorizontalGroup(
            researchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, researchPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        researchPanelLayout.setVerticalGroup(
            researchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(researchPanelLayout.createSequentialGroup()
                .addGroup(researchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        logoutPanel.setBackground(new java.awt.Color(51, 0, 51));
        logoutPanel.setForeground(new java.awt.Color(255, 255, 255));
        logoutPanel.setPreferredSize(new java.awt.Dimension(270, 70));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(15, 19, 52));
        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Logout");

        jLabel17.setBackground(new java.awt.Color(15, 19, 52));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\logouticon.png")); // NOI18N

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGroup(logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        coursePanel.setBackground(new java.awt.Color(51, 0, 51));
        coursePanel.setForeground(new java.awt.Color(255, 255, 255));
        coursePanel.setPreferredSize(new java.awt.Dimension(270, 70));
        coursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coursePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coursePanelMouseExited(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(15, 19, 52));
        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Student's Result");

        jLabel19.setBackground(new java.awt.Color(15, 19, 52));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scholarshipmanagement/research.png"))); // NOI18N

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(30, 30, 30))
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inboxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(professorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scholarshipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(universityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(researchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(coursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scholarshipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(researchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 740));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(750, 570));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1330, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inboxPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxPanelMouseClicked
        jDesktopPane1.removeAll();
        Inbox temp = new Inbox(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_inboxPanelMouseClicked

    private void inboxPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxPanelMouseEntered
        //System.out.println("Mouse Entered");
        inboxPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
        
    }//GEN-LAST:event_inboxPanelMouseEntered

    private void inboxPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxPanelMouseExited
        //System.out.println("Mouse Exited");
        inboxPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_inboxPanelMouseExited

    private void professorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professorPanelMouseClicked
        jDesktopPane1.removeAll();
        ProfessorProfile temp = new ProfessorProfile(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_professorPanelMouseClicked

    private void professorPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professorPanelMouseEntered
        professorPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_professorPanelMouseEntered

    private void professorPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professorPanelMouseExited
        professorPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_professorPanelMouseExited

    private void universityPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityPanelMouseEntered
        universityPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_universityPanelMouseEntered

    private void universityPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityPanelMouseClicked
        jDesktopPane1.removeAll();
        ProfessorUniversity temp = new ProfessorUniversity(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
        
    }//GEN-LAST:event_universityPanelMouseClicked

    private void universityPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityPanelMouseExited
        universityPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_universityPanelMouseExited

    private void scholarshipPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scholarshipPanelMouseClicked
        jDesktopPane1.removeAll();
        ProfessorScholarship temp = new ProfessorScholarship(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_scholarshipPanelMouseClicked

    private void scholarshipPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scholarshipPanelMouseEntered
        scholarshipPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_scholarshipPanelMouseEntered

    private void scholarshipPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scholarshipPanelMouseExited
        scholarshipPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_scholarshipPanelMouseExited

    private void studentPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentPanelMouseClicked
        jDesktopPane1.removeAll();
        ProfessorStudent temp = new ProfessorStudent(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_studentPanelMouseClicked

    private void studentPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentPanelMouseEntered
        studentPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_studentPanelMouseEntered

    private void studentPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentPanelMouseExited
        studentPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_studentPanelMouseExited

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Dashboard temp = new Dashboard(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        // TODO add your handling code here:
        dashboardPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        // TODO add your handling code here:
        dashboardPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void researchPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchPanelMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        ProfessorStudentResearchPaper temp = new ProfessorStudentResearchPaper(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_researchPanelMouseClicked

    private void researchPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchPanelMouseEntered
        // TODO add your handling code here:
        researchPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_researchPanelMouseEntered

    private void researchPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchPanelMouseExited
        // TODO add your handling code here:
        researchPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_researchPanelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int query = JOptionPane.showConfirmDialog(this, "Are you sure you want to Log Out?","Confirm", JOptionPane.OK_CANCEL_OPTION);
        if(query==0)
        {
            new Login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered
        // TODO add your handling code here:
        logoutPanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited
        // TODO add your handling code here:
        logoutPanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_logoutPanelMouseExited

    private void coursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursePanelMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        StudentGrade temp = new StudentGrade(ProfId);
        jDesktopPane1.add(temp).setVisible(true);
    }//GEN-LAST:event_coursePanelMouseClicked

    private void coursePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursePanelMouseEntered
        // TODO add your handling code here:
        coursePanel.setBorder(new MatteBorder(5,5,5,5,new Color(152,115,152)));
    }//GEN-LAST:event_coursePanelMouseEntered

    private void coursePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursePanelMouseExited
        // TODO add your handling code here:
        coursePanel.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_coursePanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coursePanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel inboxPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel professorPanel;
    private javax.swing.JPanel researchPanel;
    private javax.swing.JPanel scholarshipPanel;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JPanel universityPanel;
    // End of variables declaration//GEN-END:variables
}
