/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarshipmanagement;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ProfessorInformation extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorDetails
     */
    
    ArrayList<ProfessorInfo> arr = new ArrayList ();
    ArrayList<ProfessorExpertiseInfo> arr1 = new ArrayList ();
    String StudentId, ProfId;
    
    public ProfessorInformation() {
        initComponents();
    }
    public ProfessorInformation(String StudentId, String ProfId) {
        this.StudentId = StudentId;
        this.ProfId = ProfId;
        initComponents();
        arr = new ConnectMSSQL().getProfessorInfo("where ProfID = "+Integer.valueOf(ProfId));
        arr1 = new ConnectMSSQL().getProfessorExpertiseInfo("where ProfID = "+Integer.valueOf(ProfId));
        System.out.println(arr.size());
        ProfessorInfo user = arr.get(0);
        ProfessorExpertiseInfo user1 = arr1.get(0);
        
        
        profid.setText(Integer.toString(user.getProfId()));
        profname.setText(user.getFirstName());
        profuni.setText(Integer.toString(user.getUniId()));
        profemail.setText(user.getEmail());
        profedu.setText(user.getEduBackground());
        proffunding.setText(user.getFunding());
        profseat.setText(Integer.toString(user.getNoSeats()));
        profdept.setText(user.getDepartment());
        profinterest.setText(user1.getInterest());
        profexpertise.setText(user1.getExpertise());
        
        InputStream in = new ByteArrayInputStream(user.getPicture());
        BufferedImage img = null;
        try
        {
            img = ImageIO.read(in);  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        System.out.print(image.getWidth());
        System.out.print(image.getHeight());
        Image dimg = img.getScaledInstance(200,200,Image.SCALE_SMOOTH);
        Icon icon = new ImageIcon(dimg);
        image.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        proffunding = new javax.swing.JTextField();
        profuni = new javax.swing.JTextField();
        profemail = new javax.swing.JTextField();
        profname = new javax.swing.JTextField();
        profseat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        profid = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        profexpertise = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        profinterest = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        profMessage = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        profdept = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        profedu = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 730));
        setPreferredSize(new java.awt.Dimension(1540, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(149, 113, 91));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Professor Information");

        backbtn.setBackground(new java.awt.Color(128, 93, 72));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 619, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 70));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Professor Id :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("University :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Educational Background");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Funding :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Message :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        proffunding.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        proffunding.setEnabled(false);
        getContentPane().add(proffunding, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 420, 40));

        profuni.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profuni.setEnabled(false);
        getContentPane().add(profuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 420, 40));

        profemail.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profemail.setEnabled(false);
        profemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profemailActionPerformed(evt);
            }
        });
        getContentPane().add(profemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 420, 40));

        profname.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profname.setEnabled(false);
        getContentPane().add(profname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 420, 40));

        profseat.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profseat.setEnabled(false);
        getContentPane().add(profseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, 450, 40));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No of Seats :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, -1, 40));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Interest :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, -1, 40));
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 200, 200));

        sendBtn.setBackground(new java.awt.Color(128, 93, 72));
        sendBtn.setText("SEND");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 100, 30));

        profid.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profid.setEnabled(false);
        getContentPane().add(profid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 420, 40));

        profexpertise.setColumns(20);
        profexpertise.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profexpertise.setRows(5);
        profexpertise.setEnabled(false);
        jScrollPane4.setViewportView(profexpertise);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 450, 60));

        profinterest.setColumns(20);
        profinterest.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profinterest.setRows(5);
        profinterest.setEnabled(false);
        jScrollPane3.setViewportView(profinterest);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, 450, 60));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Department :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, -1, 40));

        profMessage.setColumns(20);
        profMessage.setRows(5);
        jScrollPane2.setViewportView(profMessage);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 420, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expertise :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, -1, 40));

        profdept.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profdept.setEnabled(false);
        getContentPane().add(profdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 450, 40));

        profedu.setColumns(20);
        profedu.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        profedu.setRows(5);
        profedu.setEnabled(false);
        jScrollPane1.setViewportView(profedu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 420, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\src\\scholarshipmanagement\\juj.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 730));

        setSize(new java.awt.Dimension(1563, 781));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        //StudentDashboard sp = new StudentDashboard(StudentId);
        //sp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed

    private void profemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profemailActionPerformed

    Connection con1;
    PreparedStatement insert;
    
    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        String message = profMessage.getText();
        
        if(profMessage.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Message Field is Empty", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con1 = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Scholarship;selectMethod=cursor", "sa", "123456");
                insert = con1.prepareStatement("insert into StudentMessage(StudentId, TextMessage, ProfId)values(?,?,?)");
                insert.setString(1,StudentId);
                insert.setString(2,message);
                insert.setString(3,ProfId);
                insert.executeUpdate();
              
                JOptionPane.showMessageDialog(this,"Message sent successfully");
            
                profMessage.setText("");
                profMessage.requestFocus();
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RegProfessor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(RegProfessor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea profMessage;
    private javax.swing.JTextField profdept;
    private javax.swing.JTextArea profedu;
    private javax.swing.JTextField profemail;
    private javax.swing.JTextArea profexpertise;
    private javax.swing.JTextField proffunding;
    private javax.swing.JTextField profid;
    private javax.swing.JTextArea profinterest;
    private javax.swing.JTextField profname;
    private javax.swing.JTextField profseat;
    private javax.swing.JTextField profuni;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
