/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package scholarshipmanagement;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox;
import javax.swing.JTable;

/**
 *
 * @author SARK
 */
public class ProfessorStudent extends javax.swing.JInternalFrame {

    /** Creates new form PackageInfo */
    String ProfId;
    int currentLength = 0;
    int modIndex  =0;
    ArrayList<StudentInfo> arr = new ArrayList ();
    
    public ProfessorStudent() {
        initComponents();
        
    }
    
    public ProfessorStudent(String ProfId) {
        this.ProfId = ProfId;
        initComponents();
        
        arr = new ConnectMSSQL().getStudentInfo("where  exists (Select StudentID from Student ) ");
        
        stuTable.setDefaultEditor(Object.class, null);
        
        clearTable(stuTable);
        
        if((modIndex+1)*8>arr.size())
            currentLength = arr.size()%8;
        else currentLength = 8;
        
        for(int i=0;i<currentLength;i++)
        {        
            stuTable.getModel().setValueAt(arr.get(i).getStudentID(), i, 0);
            stuTable.getModel().setValueAt(arr.get(i).getFirstName(),i, 1);
            stuTable.getModel().setValueAt(arr.get(i).getLastName(),i, 2);
            stuTable.getModel().setValueAt(arr.get(i).getDepartment(),i, 3);
            stuTable.getModel().setValueAt(arr.get(i).getAverageGrade(),i, 4);
            stuTable.getModel().setValueAt(arr.get(i).getYear(),i, 5);
            stuTable.getModel().setValueAt("Details", i,6);
            stuTable.getModel().setValueAt("Academic", i,7);
            
            
        }
        stuTable.getColumn("Action1").setCellRenderer(new ButtonRenderer(currentLength));
        stuTable.getColumn("Action1").setCellEditor(new ButtonEditor(new JCheckBox(),stuTable));
        
        stuTable.getColumn("Action2").setCellRenderer(new ButtonRenderer(currentLength));
        stuTable.getColumn("Action2").setCellEditor(new ButtonEditor(new JCheckBox(),stuTable));
        
        prevButton1.setVisible(false);
        if(arr.size()<=8)
            nextButton1.setVisible(false);
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nextButton1 = new javax.swing.JButton();
        deptSearch = new javax.swing.JTextField();
        searchbtnProf1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reset1btn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        avgTo = new javax.swing.JTextField();
        yearTo = new javax.swing.JTextField();
        yearFrom = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        avgFrom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prevButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(750, 570));
        setMinimumSize(new java.awt.Dimension(750, 570));
        setPreferredSize(new java.awt.Dimension(1320, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 111, 111));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(532, 532, 532))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 60));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("To :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 40, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Average Grade : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, 30));

        nextButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nextButton1.setText("Next");
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, -1));

        deptSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deptSearch.setPreferredSize(new java.awt.Dimension(6, 35));
        deptSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptSearchActionPerformed(evt);
            }
        });
        getContentPane().add(deptSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 230, 30));

        searchbtnProf1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\ScholarshipManagement\\image\\transparency.png")); // NOI18N
        searchbtnProf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnProf1ActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtnProf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 80, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("From :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, 30));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("From :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, 30));

        reset1btn1.setText("RESET");
        reset1btn1.setPreferredSize(new java.awt.Dimension(57, 33));
        reset1btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 80, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 50, 30));

        avgTo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        avgTo.setPreferredSize(new java.awt.Dimension(6, 35));
        avgTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgToActionPerformed(evt);
            }
        });
        getContentPane().add(avgTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 90, 30));

        yearTo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        yearTo.setPreferredSize(new java.awt.Dimension(6, 35));
        yearTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearToActionPerformed(evt);
            }
        });
        getContentPane().add(yearTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 90, 30));

        yearFrom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        yearFrom.setPreferredSize(new java.awt.Dimension(6, 35));
        yearFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearFromActionPerformed(evt);
            }
        });
        getContentPane().add(yearFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 90, 30));

        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "FirstName", "LastName", "Department", "Average Grade", "Year", "Action1", "Action2"
            }
        ));
        stuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(stuTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 1140, 160));

        avgFrom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        avgFrom.setPreferredSize(new java.awt.Dimension(6, 35));
        avgFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgFromActionPerformed(evt);
            }
        });
        getContentPane().add(avgFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, 30));

        jLabel10.setBackground(new java.awt.Color(102, 0, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Department :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, 30));

        prevButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prevButton1.setText("Prev");
        prevButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(prevButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scholarshipmanagement/8812be4cab3c6b76e334e68c15c9ef13.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        // TODO add your handling code here:
        modIndex++;
        prevButton1.setVisible(true);
        if((modIndex+1)*8>=arr.size())
        nextButton1.setVisible(false);
        clearTable(stuTable);
        if((modIndex+1)*8>arr.size())
        currentLength = arr.size()%8;
        else currentLength = 8;
        for(int i=0;i<currentLength;i++)
        {
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getStudentID(),i, 0);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getFirstName(),i, 1);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getLastName(),i, 2);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getDepartment(),i, 3);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getAverageGrade(),i, 4);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getYear(),i, 5);

            stuTable.getModel().setValueAt("Details", i,6);
            stuTable.getModel().setValueAt("Academic", i,7);

        }
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void deptSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptSearchActionPerformed

    private void searchbtnProf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnProf1ActionPerformed
        // TODO add your handling code here:
        String query = "";
        String temp ;
        Integer tempFrom, tempTo;
        Float tempFrom1, tempTo1; //avgsearch

        temp = deptSearch.getText();
        if(temp.equals("")==false && temp.length()>0)
        {
            if(query.length()==0)
            {
                query+= "where Department='"+temp+"'";
            }
            else query+="and Department='"+temp+"'";
        }
        
        if((yearFrom.getText().toString().equals("")  && yearTo.getText().toString().equals("")) || (yearFrom.getText().length()==0 && yearTo.getText().length() ==0 ))
        {
            if(query.length()==0)
            {
                query+= "where Year between 1 AND 4";
            }
            else query+="and Year between 1 AND 4";
            
        }
        else if (yearFrom.getText().length()==0 || yearTo.getText().length() ==0 ){
            JOptionPane.showMessageDialog(this, "Both of the Year Have to be Filled", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        else if(yearFrom.getText().toString().equals("")==false && yearTo.getText().toString().equals("To")==false){
            tempFrom = Integer.valueOf(yearFrom.getText());
            tempTo = Integer.valueOf(yearTo.getText());
            if(query.length()==0)
            {
                query+= "where Year between "+tempFrom+" AND "+tempTo;
            }
            else query+="and Year between "+tempFrom+" AND "+tempTo;
            
        }
        
        
        if((avgFrom.getText().toString().equals("")  && avgFrom.getText().toString().equals("")) || (avgFrom.getText().length()==0 && avgTo.getText().length() ==0 ))
        {
            if(query.length()==0)
            {
                query+= "where AverageGrade between 0.00 AND 4.00";
            }
            else query+="and AverageGrade between 0.00 AND 4.00";
            
        }
        else if (avgFrom.getText().length()==0 || avgFrom.getText().length() ==0 ){
            JOptionPane.showMessageDialog(this, "Both of the Grade Have to be Filled", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        else if(avgFrom.getText().toString().equals("")==false && avgFrom.getText().toString().equals("To")==false){
            tempFrom = Integer.valueOf(avgFrom.getText());
            tempTo = Integer.valueOf(avgFrom.getText());
            if(query.length()==0)
            {
                query+= "where AverageGrade between "+tempFrom+" AND "+tempTo;
            }
            else query+="and AverageGrade between "+tempFrom+" AND "+tempTo;
            
        }
       

        arr.clear();
        arr = new ConnectMSSQL().getStudentInfo(query);

        modIndex = 0;

        clearTable(stuTable);

        if((modIndex+1)*8>arr.size())
        currentLength = arr.size()%8;
        else currentLength = 8;

        for(int i=0;i<currentLength;i++)
        {
            stuTable.getModel().setValueAt(arr.get(i).getStudentID(),i, 0);
            stuTable.getModel().setValueAt(arr.get(i).getFirstName(),i, 1);
            stuTable.getModel().setValueAt(arr.get(i).getLastName(),i, 2);
            stuTable.getModel().setValueAt(arr.get(i).getDepartment(),i, 3);
            stuTable.getModel().setValueAt(arr.get(i).getAverageGrade(),i, 4);
            stuTable.getModel().setValueAt(arr.get(i).getYear(),i, 5);
            stuTable.getModel().setValueAt("Details", i,6);
            stuTable.getModel().setValueAt("Academic", i,7);
        }

        prevButton1.setVisible(false);
        if(arr.size()<=8)
        nextButton1.setVisible(false);
        else
        nextButton1.setVisible(true);
    }//GEN-LAST:event_searchbtnProf1ActionPerformed

    private void reset1btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1btn1ActionPerformed
        // TODO add your handling code here:
        deptSearch.setText("");
        yearFrom.setText("");
        yearTo.setText("");
        avgFrom.setText("");
        avgTo.setText("");
    }//GEN-LAST:event_reset1btn1ActionPerformed

    private void avgToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgToActionPerformed

    private void yearToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearToActionPerformed

    private void yearFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFromActionPerformed

    private void stuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuTableMouseClicked
        // TODO add your handling code here:
        int row = stuTable.getSelectedRow();
        int col = stuTable.getSelectedColumn();
        System.out.println(row +" "+ col+" "+arr.size());;
        if(col==7 && row<currentLength)
        {
            new StudentGradeResearch(ProfId,Integer.toString(arr.get(row+8*modIndex).getStudentID())).setVisible(true);
        }
        if(col==6 && row<currentLength)
        {
            new StudentDetails(ProfId,Integer.toString(arr.get(row+8*modIndex).getStudentID())).setVisible(true);
        }
    }//GEN-LAST:event_stuTableMouseClicked

    private void avgFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgFromActionPerformed

    private void prevButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButton1ActionPerformed
        // TODO add your handling code here:
        modIndex--;
        if(modIndex==0)
        prevButton1.setVisible(false);
        nextButton1.setVisible(true);
        clearTable(stuTable);
        if((modIndex+1)*8>arr.size())
        currentLength = arr.size()%8;
        else currentLength = 8;
        for(int i=0;i<currentLength;i++)
        {
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getStudentID(),i, 0);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getFirstName(),i, 1);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getLastName(),i, 2);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getDepartment(),i, 3);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getAverageGrade(),i, 4);
            stuTable.getModel().setValueAt(arr.get(i+8*modIndex).getYear(),i, 5);

            stuTable.getModel().setValueAt("Details", i,6);
            stuTable.getModel().setValueAt("Academic", i,7);
        }
    }//GEN-LAST:event_prevButton1ActionPerformed

    public static void clearTable(final JTable table) {
        for (int i = 0; i < table.getRowCount(); i++) {
            for(int j = 0; j < table.getColumnCount(); j++) {
                table.setValueAt("", i, j);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avgFrom;
    private javax.swing.JTextField avgTo;
    private javax.swing.JTextField deptSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton1;
    private javax.swing.JButton prevButton1;
    private javax.swing.JButton reset1btn1;
    private javax.swing.JButton searchbtnProf1;
    private javax.swing.JTable stuTable;
    private javax.swing.JTextField yearFrom;
    private javax.swing.JTextField yearTo;
    // End of variables declaration//GEN-END:variables

}
