/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarshipmanagement;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.image.ImageFilter;
import javax.swing.JFileChooser;
import java.io.File;      
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author HP
 */
public class ProfessorEdit extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorDetails
     */
    
    ArrayList<ProfessorInfo> arr = new ArrayList ();
    ArrayList<ProfessorExpertiseInfo> arr1 = new ArrayList ();
    String ProfId;
    ProfessorInfo user,u;
    ProfessorExpertiseInfo user1;
    
    
    public ProfessorEdit() {
        initComponents();
    }
    public ProfessorEdit(ProfessorInfo user, ProfessorExpertiseInfo user1, String ProfId) {
        this.ProfId = ProfId;
        this.user = user;
        this.user1 = user1;
        initComponents();
        arr = new ConnectMSSQL().getProfessorInfo("where ProfID = "+Integer.valueOf(ProfId));
        arr1 = new ConnectMSSQL().getProfessorExpertiseInfo("where ProfID = "+Integer.valueOf(ProfId));
        System.out.println(arr.size());
        user = arr.get(0);
        
        
        footerName.setOpaque(true);
        footerEmail.setOpaque(true);
        footerDepartment.setOpaque(true);
        footerUniversity.setOpaque(true);
        footerFunding.setOpaque(true);
        footerEdu.setOpaque(true);
        footerInterest.setOpaque(true);
        footerExpertise.setOpaque(true);
        footerStudent.setOpaque(true);
        
        
        footerName.setVisible(false);
        footerEmail.setVisible(false);
        footerDepartment.setVisible(false);
        footerUniversity.setVisible(false);
        footerFunding.setVisible(false);
        footerEdu.setVisible(false);
        footerInterest.setVisible(false);
        footerExpertise.setVisible(false);
        footerStudent.setVisible(false);
        
        //jLabel3.setText("<html>Educational<br>Background</html>");
        
        
        profname.setText(user.getFirstName());
        profuni.setText(Integer.toString(user.getUniId()));
        profemail.setText(user.getEmail());
        profedu.setText(user.getEduBackground());
        proffunding.setText(user.getFunding());
        profseat.setText(Integer.toString(user.getNoSeats()));
        profdept.setText(user.getDepartment());
        profinterest.setText(user1.getInterest());
        profexpertise.setText(user1.getExpertise());
        
        
        InputStream in = new ByteArrayInputStream(user.getPicture());
        BufferedImage img = null;
        try
        {
            img = ImageIO.read(in);  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        System.out.print(image1.getWidth());
        System.out.print(image1.getHeight());
        Image dimg = img.getScaledInstance(200,200,Image.SCALE_SMOOTH);
        Icon icon = new ImageIcon(dimg);
        image1.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        profuni = new javax.swing.JTextField();
        footerUniversity = new javax.swing.JLabel();
        profemail = new javax.swing.JTextField();
        footerEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profedu = new javax.swing.JTextArea();
        footerEdu = new javax.swing.JLabel();
        profinterest = new javax.swing.JTextField();
        footerInterest = new javax.swing.JLabel();
        proffunding = new javax.swing.JTextField();
        footerFunding = new javax.swing.JLabel();
        profexpertise = new javax.swing.JTextField();
        footerExpertise = new javax.swing.JLabel();
        profdept = new javax.swing.JTextField();
        footerDepartment = new javax.swing.JLabel();
        profseat = new javax.swing.JTextField();
        footerStudent = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        profname = new javax.swing.JTextField();
        footerName = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(193, 72, 126));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Professor Information");

        backbtn.setBackground(new java.awt.Color(213, 132, 156));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setText("Full Name :");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel5.setText("Expertise :");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel6.setText("University :");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel7.setText("Interest :");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel8.setText("Funding :");

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel9.setText("Email :");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel13.setText("Educational ");

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel14.setText("No of Seats :");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel15.setText("Department :");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel4.setText("Background :");

        profuni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profuni.setPreferredSize(new java.awt.Dimension(59, 27));
        profuni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profuniKeyTyped(evt);
            }
        });

        footerUniversity.setBackground(new java.awt.Color(255, 0, 0));
        footerUniversity.setText("University is Empty");

        profemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profemail.setPreferredSize(new java.awt.Dimension(59, 27));
        profemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profemailKeyTyped(evt);
            }
        });

        footerEmail.setBackground(new java.awt.Color(255, 0, 0));
        footerEmail.setText("Email is Empty");

        profedu.setColumns(20);
        profedu.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        profedu.setRows(5);
        profedu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profeduKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(profedu);

        footerEdu.setBackground(new java.awt.Color(255, 0, 0));
        footerEdu.setText("Education is Empty");

        profinterest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profinterest.setPreferredSize(new java.awt.Dimension(59, 27));
        profinterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profinterestKeyTyped(evt);
            }
        });

        footerInterest.setBackground(new java.awt.Color(255, 0, 0));
        footerInterest.setText("Interest is Empty");

        proffunding.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        proffunding.setPreferredSize(new java.awt.Dimension(59, 27));
        proffunding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proffundingActionPerformed(evt);
            }
        });
        proffunding.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                proffundingKeyTyped(evt);
            }
        });

        footerFunding.setBackground(new java.awt.Color(255, 0, 0));
        footerFunding.setText("Funding is Empty");

        profexpertise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profexpertise.setPreferredSize(new java.awt.Dimension(59, 27));
        profexpertise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profexpertiseKeyTyped(evt);
            }
        });

        footerExpertise.setBackground(new java.awt.Color(255, 0, 0));
        footerExpertise.setText("Expertise is Empty");

        profdept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profdept.setPreferredSize(new java.awt.Dimension(59, 27));
        profdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profdeptActionPerformed(evt);
            }
        });
        profdept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profdeptKeyTyped(evt);
            }
        });

        footerDepartment.setBackground(new java.awt.Color(255, 0, 0));
        footerDepartment.setText("Department is Empty");

        profseat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profseat.setPreferredSize(new java.awt.Dimension(59, 27));
        profseat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profseatKeyTyped(evt);
            }
        });

        footerStudent.setBackground(new java.awt.Color(255, 0, 0));
        footerStudent.setText("No of Student is Empty");

        jLabel11.setText("jLabel11");

        jButton1.setText("Add Image");

        profname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profname.setMinimumSize(new java.awt.Dimension(60, 30));
        profname.setPreferredSize(new java.awt.Dimension(60, 30));
        profname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profnameActionPerformed(evt);
            }
        });
        profname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profnameKeyTyped(evt);
            }
        });

        footerName.setBackground(new java.awt.Color(255, 0, 0));
        footerName.setText("Name is not valid");

        btnupdate.setBackground(new java.awt.Color(1, 148, 171));
        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnupdate.setText("Save");
        btnupdate.setBorder(new javax.swing.border.MatteBorder(null));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jButton2.setText("Add Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(footerName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(footerEmail)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(footerStudent)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(profinterest, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(profseat, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(footerInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)))))
                            .addComponent(footerEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(footerUniversity)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(profname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profuni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(459, 459, 459))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(footerDepartment)
                                        .addComponent(profdept, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(proffunding, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(footerExpertise)
                                            .addComponent(profexpertise, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                                        .addComponent(footerFunding, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(64, 64, 64)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(350, 350, 350)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(555, 555, 555)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(profname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(0, 0, 0)
                                        .addComponent(footerName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(profuni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(0, 0, 0)
                                        .addComponent(footerUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(profemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, 0)
                                        .addComponent(footerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jButton2)))
                                        .addGap(18, 18, 18)
                                        .addComponent(profdept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(footerDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(189, 189, 189))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(footerEdu)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(profexpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(footerExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(profinterest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(footerInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(proffunding, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profseat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(footerFunding, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(footerStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1260, 620));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 730));

        setSize(new java.awt.Dimension(1318, 781));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        //ProfessorProfile p = new ProfessorProfile(ProfId);
        //p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed

    private void profuniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profuniKeyTyped
        if(profuni.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerUniversity.setVisible(true);
        else
        footerUniversity.setVisible(false);
    }//GEN-LAST:event_profuniKeyTyped

    private void profemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profemailKeyTyped
        if(profemail.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerEmail.setVisible(true);
        else
        footerEmail.setVisible(false);
    }//GEN-LAST:event_profemailKeyTyped

    private void profeduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profeduKeyTyped
        if(profedu.getText().length()==0  && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerEdu.setVisible(true);
        else
        footerEdu.setVisible(false);
    }//GEN-LAST:event_profeduKeyTyped

    private void profinterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profinterestKeyTyped
        if(profinterest.getText().length()==0  && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
            footerInterest.setVisible(true);
        else
            footerInterest.setVisible(false);
    }//GEN-LAST:event_profinterestKeyTyped

    private void proffundingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proffundingKeyTyped
        // TODO add your handling code here:
        if(proffunding.getText().length()==0  && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
            footerFunding.setVisible(true);
        else
            footerFunding.setVisible(false);
    }//GEN-LAST:event_proffundingKeyTyped

    private void profexpertiseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profexpertiseKeyTyped
        if(profinterest.getText().length()==0  && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
            footerExpertise.setVisible(true);
        else
            footerExpertise.setVisible(false);
    }//GEN-LAST:event_profexpertiseKeyTyped

    private void profdeptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profdeptKeyTyped
        // TODO add your handling code here:
        if(profdept.getText().length()==0  && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
            footerDepartment.setVisible(true);
        else
            footerDepartment.setVisible(false);
    }//GEN-LAST:event_profdeptKeyTyped

    private void profseatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profseatKeyTyped
        // TODO add your handling code here:
        if(profseat.getText().length()==0  && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
            footerStudent.setVisible(true);
        else
            footerStudent.setVisible(false);
    }//GEN-LAST:event_profseatKeyTyped

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if(profname.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Name is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profuni.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "University is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profemail.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Email is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profedu.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Education is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profinterest.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Interest is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profseat.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "No. of Seats is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profdept.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Department is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(profexpertise.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Expertise is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(proffunding.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Funding is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            user.setFirstName(profname.getText());
            user.setUniId(Integer.parseInt(profuni.getText()));
            user.setEmail(profemail.getText());
            user.setEduBackground(profedu.getText());
            user.setNoSeats(Integer.parseInt(profseat.getText()));
            user.setDepartment(profdept.getText());
            user.setFunding(proffunding.getText());
            user1.setInterest(profinterest.getText());
            user1.setExpertise(profexpertise.getText());
            user1.setProfId(Integer.parseInt(ProfId));
            Icon icon = image1.getIcon();
            BufferedImage bi = new BufferedImage(icon.getIconWidth(),icon.getIconHeight(),BufferedImage.TYPE_INT_RGB);
            Graphics g = bi.createGraphics();

            icon.paintIcon(null, g, 0,0);
            g.setColor(Color.WHITE);
            g.drawString("",10,20);
            g.dispose();

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try
            {

                ImageIO.write(bi, "jpg", baos);
            }
            catch(IOException e)
            {
                e.printStackTrace();
            }
            user.setPicture(baos.toByteArray());
            
            try
            {
                new ConnectMSSQL().updateProfessor(user);
                new ConnectMSSQL().updateProfessorExpertise(user1);
          
                JOptionPane.showMessageDialog(this, "Updated Successfully","Added",JOptionPane.INFORMATION_MESSAGE);
                backbtnActionPerformed(evt);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void profnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profnameActionPerformed

    private void profnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profnameKeyTyped

        if(profname.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerName.setVisible(true);
        else
        footerName.setVisible(false);
    }//GEN-LAST:event_profnameKeyTyped

    private void proffundingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proffundingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proffundingActionPerformed

    private void profdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profdeptActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg"));

        fileChooser.setAcceptAllFileFilterUsed(false);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            //System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            String IMG_PATH = selectedFile.getAbsolutePath().toString();
            try {
                BufferedImage img = ImageIO.read(new File(IMG_PATH));
                Image dimg = img.getScaledInstance(200, 200,
                    Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(dimg);
                image1.setIcon(icon);
                //JOptionPane.showMessageDialog(null, label);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    Connection con1;
    PreparedStatement insert;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel footerDepartment;
    private javax.swing.JLabel footerEdu;
    private javax.swing.JLabel footerEmail;
    private javax.swing.JLabel footerExpertise;
    private javax.swing.JLabel footerFunding;
    private javax.swing.JLabel footerInterest;
    private javax.swing.JLabel footerName;
    private javax.swing.JLabel footerStudent;
    private javax.swing.JLabel footerUniversity;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField profdept;
    private javax.swing.JTextArea profedu;
    private javax.swing.JTextField profemail;
    private javax.swing.JTextField profexpertise;
    private javax.swing.JTextField proffunding;
    private javax.swing.JTextField profinterest;
    private javax.swing.JTextField profname;
    private javax.swing.JTextField profseat;
    private javax.swing.JTextField profuni;
    // End of variables declaration//GEN-END:variables
}
