/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarshipmanagement;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class StudentUpdate extends javax.swing.JFrame {

    /**
     * Creates new form StudentUpdate
     */
    String StudentId;
    ArrayList<StudentInfo> arr  = new ArrayList<StudentInfo> ();
    
    public StudentUpdate() {
        initComponents();
    }
    
    public StudentUpdate(String studentId) {
        this.StudentId  =studentId;
        initComponents();
        arr = new ConnectMSSQL().getStudentInfo("where StudentID = "+Integer.valueOf(StudentId));
        StudentInfo user = arr.get(0);
        
        System.out.println(user.getPassword());
        footerFirstName.setOpaque(true);
        footerLastName.setOpaque(true);
        footerDept.setOpaque(true);
        footerSession.setOpaque(true);
        footerYear.setOpaque(true);
        footerSemester.setOpaque(true);
        footerEmail.setOpaque(true);
        footerPassword.setOpaque(true);
        footerGrade.setOpaque(true);
        footerCredit.setOpaque(true);
        footerExtra.setOpaque(true);
        footerBlog.setOpaque(true);
        footerRef.setOpaque(true);
        footerPassword.setOpaque(true);
        
        
        
        
        
        footerFirstName.setVisible(false);
        footerLastName.setVisible(false);
        footerDept.setVisible(false);
        footerSession.setVisible(false);
        footerYear.setVisible(false);
        footerSemester.setVisible(false);
        footerEmail.setVisible(false);
        footerPassword.setVisible(false);
        footerGrade.setVisible(false);
        footerCredit.setVisible(false);
        footerExtra.setVisible(false);
        footerBlog.setVisible(false);
        footerRef.setVisible(false);
        footerPassword.setVisible(false);
        
        id.setText(Integer.toString(user.getStudentID()));
        firstName.setText(user.getFirstName());
        lastName.setText(user.getLastName());
        department.setText(user.getDepartment());
        session.setText(user.getSession());
        year.setText(Integer.toString(user.getYear()));
        semester.setText(Integer.toString(user.getSemester()));
        email.setText(user.getEmail());
        averageGrade.setText(Double.toString(user.getAverageGrade()));
        credit.setText(Double.toString(user.getCompletedCredit()));
        extra.setText(user.getExtracurricularActivities());
        blog.setText(user.getBlog());
        ref.setText(user.getReference());
        password.setText(user.getPassword());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        footerFirstName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        session = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        averageGrade = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        footerYear = new javax.swing.JLabel();
        footerLastName = new javax.swing.JLabel();
        footerDept = new javax.swing.JLabel();
        footerRef = new javax.swing.JLabel();
        footerSession = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        credit = new javax.swing.JTextField();
        extra = new javax.swing.JTextField();
        blog = new javax.swing.JTextField();
        ref = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        footerBlog = new javax.swing.JLabel();
        footerExtra = new javax.swing.JLabel();
        footerCredit = new javax.swing.JLabel();
        footerEmail = new javax.swing.JLabel();
        footerSemester = new javax.swing.JLabel();
        footerGrade = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        footerPassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel2.setBackground(new java.awt.Color(15, 19, 52));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Information Update");

        backbtn.setBackground(new java.awt.Color(255, 51, 51));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 70));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Semester:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 130, 30));

        firstName.setPreferredSize(new java.awt.Dimension(59, 27));
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameKeyTyped(evt);
            }
        });
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 190, 30));

        footerFirstName.setBackground(new java.awt.Color(255, 0, 0));
        footerFirstName.setText("First Name is Empty");
        getContentPane().add(footerFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, 13));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Student Id:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("First Name:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Last Name:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Department:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 130, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Session:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 130, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Average Grade :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 160, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Year:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 130, 30));

        lastName.setPreferredSize(new java.awt.Dimension(59, 27));
        lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameKeyTyped(evt);
            }
        });
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 190, 30));

        department.setPreferredSize(new java.awt.Dimension(59, 27));
        department.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                departmentKeyTyped(evt);
            }
        });
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 190, 30));

        semester.setPreferredSize(new java.awt.Dimension(59, 27));
        semester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semesterKeyTyped(evt);
            }
        });
        getContentPane().add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 190, 30));

        session.setPreferredSize(new java.awt.Dimension(59, 27));
        session.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sessionKeyTyped(evt);
            }
        });
        getContentPane().add(session, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 190, 30));

        year.setPreferredSize(new java.awt.Dimension(59, 27));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearKeyTyped(evt);
            }
        });
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 190, 30));

        averageGrade.setPreferredSize(new java.awt.Dimension(59, 27));
        averageGrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                averageGradeKeyTyped(evt);
            }
        });
        getContentPane().add(averageGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 190, 30));

        id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        id.setDoubleBuffered(true);
        id.setEnabled(false);
        id.setPreferredSize(new java.awt.Dimension(59, 27));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 190, 30));

        footerYear.setBackground(new java.awt.Color(255, 0, 0));
        footerYear.setText("Year is Empty");
        getContentPane().add(footerYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 190, 13));

        footerLastName.setBackground(new java.awt.Color(255, 0, 0));
        footerLastName.setText("Last Name is Empty");
        getContentPane().add(footerLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 190, 13));

        footerDept.setBackground(new java.awt.Color(255, 0, 0));
        footerDept.setText("Department is Empty");
        getContentPane().add(footerDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 190, 13));

        footerRef.setBackground(new java.awt.Color(255, 0, 0));
        footerRef.setText("Reference is Empty");
        getContentPane().add(footerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 190, 13));

        footerSession.setBackground(new java.awt.Color(255, 0, 0));
        footerSession.setText("Session is Empty");
        getContentPane().add(footerSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 190, 13));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Completed Credit:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 170, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Extracurricular :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 170, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Blog :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 130, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Reference :");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 130, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Email:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 130, 30));

        credit.setPreferredSize(new java.awt.Dimension(59, 27));
        credit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditKeyTyped(evt);
            }
        });
        getContentPane().add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 190, 30));

        extra.setPreferredSize(new java.awt.Dimension(59, 27));
        extra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                extraKeyTyped(evt);
            }
        });
        getContentPane().add(extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 190, 30));

        blog.setPreferredSize(new java.awt.Dimension(59, 27));
        blog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                blogKeyTyped(evt);
            }
        });
        getContentPane().add(blog, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 190, 30));

        ref.setPreferredSize(new java.awt.Dimension(59, 27));
        ref.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                refKeyTyped(evt);
            }
        });
        getContentPane().add(ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, 190, 30));

        email.setPreferredSize(new java.awt.Dimension(59, 27));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 190, 30));

        footerBlog.setBackground(new java.awt.Color(255, 0, 0));
        footerBlog.setText("Blog is Empty");
        getContentPane().add(footerBlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 190, 13));

        footerExtra.setBackground(new java.awt.Color(255, 0, 0));
        footerExtra.setText("Extracurricular Activities is Empty");
        getContentPane().add(footerExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 190, 20));

        footerCredit.setBackground(new java.awt.Color(255, 0, 0));
        footerCredit.setText("Completed Credit is Empty");
        getContentPane().add(footerCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 190, 13));

        footerEmail.setBackground(new java.awt.Color(255, 0, 0));
        footerEmail.setText("Email is Empty");
        getContentPane().add(footerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 190, 13));

        footerSemester.setBackground(new java.awt.Color(255, 0, 0));
        footerSemester.setText("Semester is Empty");
        getContentPane().add(footerSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 190, 13));

        footerGrade.setBackground(new java.awt.Color(255, 0, 0));
        footerGrade.setText("Average Grade is Empty");
        getContentPane().add(footerGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 190, 13));

        updateButton.setBackground(new java.awt.Color(233, 85, 15));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 110, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Password:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 160, 30));

        password.setPreferredSize(new java.awt.Dimension(59, 27));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 190, 30));

        footerPassword.setBackground(new java.awt.Color(255, 0, 0));
        footerPassword.setText("Password is Empty");
        getContentPane().add(footerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 190, 13));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scholarshipmanagement/4.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1300, 580));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1190, 540));

        setSize(new java.awt.Dimension(1318, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        new Student(StudentId).setVisible(true);
        this.setVisible(false);
   ;
    }//GEN-LAST:event_backbtnActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if(firstName.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "First Name is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(lastName.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Last Name is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(department.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Department is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(session.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Session is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(email.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Email is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!validate(email.getText()))
        {
            JOptionPane.showMessageDialog(this, "Email is not Valid","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(year.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Year is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }

        else if(semester.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Semester is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(password.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Password is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(averageGrade.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Average Grade No is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }

        else if(credit.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Completed Credit is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(extra.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Extracurricular Activities is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(blog.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Blog is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(ref.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Reference is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            StudentInfo user = new StudentInfo();

            user.setStudentID(arr.get(0).getStudentID());
            user.setFirstName(firstName.getText().toString());
            user.setLastName(lastName.getText().toString());
            user.setDepartment(department.getText().toString());
            user.setSession(session.getText().toString());
            user.setYear(Integer.valueOf(year.getText().toString()));
            user.setSemester(Integer.valueOf(semester.getText().toString()));
            user.setEmail(email.getText().toString());
            user.setPassword(password.getText().toString());
            user.setAverageGrade(Float.valueOf(averageGrade.getText().toString()));
            user.setCompletedCredit(Float.valueOf(credit.getText().toString()));
            user.setExtracurricularActivities(extra.getText().toString());
            user.setBlog(blog.getText().toString());
            user.setReference(ref.getText().toString());

            try
            {
                new ConnectMSSQL().updateStudentInfo(user);

                JOptionPane.showMessageDialog(this, "Updated Successfully","Updated",JOptionPane.INFORMATION_MESSAGE);
                backbtnActionPerformed(evt);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Occured","Error",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void refKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refKeyTyped
        if(ref.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerRef.setVisible(true);
        else
        footerRef.setVisible(false);
    }//GEN-LAST:event_refKeyTyped

    private void semesterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semesterKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }

        if((semester.getText().length()==0) && (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar()==KeyEvent.VK_DELETE || !((evt.getKeyChar() >= '0') && (evt.getKeyChar()<= '9'))))
        footerSemester.setVisible(true);
        else
        footerSemester.setVisible(false);
    }//GEN-LAST:event_semesterKeyTyped

    private void yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }

        if((year.getText().length()==0) && (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar()==KeyEvent.VK_DELETE || !((evt.getKeyChar() >= '0') && (evt.getKeyChar()<= '9'))))
        footerYear.setVisible(true);
        else
        footerYear.setVisible(false);
    }//GEN-LAST:event_yearKeyTyped

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void blogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_blogKeyTyped
        if(blog.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerBlog.setVisible(true);
        else
        footerBlog.setVisible(false);
    }//GEN-LAST:event_blogKeyTyped

    private void extraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extraKeyTyped
        if(extra.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerExtra.setVisible(true);
        else
        footerExtra.setVisible(false);
    }//GEN-LAST:event_extraKeyTyped

    private void sessionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sessionKeyTyped
        if(session.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerSession.setVisible(true);
        else
        footerSession.setVisible(false);
    }//GEN-LAST:event_sessionKeyTyped

    private void departmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departmentKeyTyped
        if(department.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerDept.setVisible(true);
        else
        footerDept.setVisible(false);
    }//GEN-LAST:event_departmentKeyTyped

    private void creditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == '.')||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }

        if((credit.getText().length()==0) && (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar()=='.' || evt.getKeyChar()==KeyEvent.VK_DELETE || !((evt.getKeyChar() >= '0') && (evt.getKeyChar()<= '9'))))
        footerCredit.setVisible(true);
        else
        footerCredit.setVisible(false);
    }//GEN-LAST:event_creditKeyTyped

    private void averageGradeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_averageGradeKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == '.')||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }

        if((averageGrade.getText().length()==0) && (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar()=='.' || evt.getKeyChar()==KeyEvent.VK_DELETE || !((evt.getKeyChar() >= '0') && (evt.getKeyChar()<= '9'))))
        footerGrade.setVisible(true);
        else
        footerGrade.setVisible(false);
    }//GEN-LAST:event_averageGradeKeyTyped

    private void lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameKeyTyped
        if(lastName.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerLastName.setVisible(true);
        else
        footerLastName.setVisible(false);
    }//GEN-LAST:event_lastNameKeyTyped

    private void firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyTyped
        if(firstName.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerFirstName.setVisible(true);
        else
        footerFirstName.setVisible(false);

    }//GEN-LAST:event_firstNameKeyTyped

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped

        if(password.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerPassword.setVisible(true);
        else
        footerPassword.setVisible(false);
    }//GEN-LAST:event_passwordKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        if(email.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
        footerEmail.setVisible(true);
        else
        footerEmail.setVisible(false);
    }//GEN-LAST:event_emailKeyTyped

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyTyped
    public boolean validate(String email)
    {
        int x = email.indexOf("@");
        if(x==-1)
            return false;
        x = email.indexOf(".", x);
        if(x==-1)
            return false;
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField averageGrade;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField blog;
    private javax.swing.JTextField credit;
    private javax.swing.JTextField department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField extra;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel footerBlog;
    private javax.swing.JLabel footerCredit;
    private javax.swing.JLabel footerDept;
    private javax.swing.JLabel footerEmail;
    private javax.swing.JLabel footerExtra;
    private javax.swing.JLabel footerFirstName;
    private javax.swing.JLabel footerGrade;
    private javax.swing.JLabel footerLastName;
    private javax.swing.JLabel footerPassword;
    private javax.swing.JLabel footerRef;
    private javax.swing.JLabel footerSemester;
    private javax.swing.JLabel footerSession;
    private javax.swing.JLabel footerYear;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField password;
    private javax.swing.JTextField ref;
    private javax.swing.JTextField semester;
    private javax.swing.JTextField session;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
